# ============================================================
# ECC + AES HYBRID ENCRYPTION
# ============================================================
#
# ECC is NOT directly encrypting the message.
#
# ECC / ECDH:
#       Establishes a shared secret
#
# SHA-256:
#       Converts the shared secret into an AES key
#
# AES:
#       Actually encrypts the message
#
#
# FLOW:
#
#       Sender private key
#              +
#       Receiver public key
#              |
#              ↓
#       ECC key agreement
#              |
#              ↓
#       Shared Secret
#              |
#              ↓
#           SHA-256
#              |
#              ↓
#          AES Key
#              |
#              ↓
#       Encrypt Message
#
#
# Receiver does the same thing:
#
#       Receiver private key
#              +
#       Sender public key
#              |
#              ↓
#       SAME Shared Secret
#              |
#              ↓
#           SHA-256
#              |
#              ↓
#          SAME AES Key
#              |
#              ↓
#       Decrypt Message
# ============================================================


from Crypto.PublicKey import ECC
from Crypto.Protocol.DH import key_agreement
from Crypto.Hash import SHA256
from Crypto.Cipher import AES


# ============================================================
# 1. GENERATE ECC KEY PAIR
# ============================================================
#
# Generates:
#
#       private_key
#       public_key
#
# curve = "P-256"
#
# P-256 is the ECC curve used in our lab code.
#
# ============================================================

def generate_ecc_keys():

    private_key = ECC.generate(curve="P-256")

    public_key = private_key.public_key()

    return private_key, public_key


# ============================================================
# 2. GENERATE SHARED SECRET
# ============================================================
#
# One side uses:
#
#       OWN private key
#             +
#       OTHER person's public key
#
# Example - Sender:
#
#       sender_private
#             +
#       receiver_public
#
#
# Example - Receiver:
#
#       receiver_private
#             +
#       sender_public
#
#
# Both sides obtain the SAME shared secret.
#
# SHA-256 is used as the KDF
# (Key Derivation Function).
#
# ============================================================

def generate_shared_secret(private_key, other_public_key):

    secret = key_agreement(
        static_priv=private_key,
        static_pub=other_public_key,
        kdf=lambda x: SHA256.new(x).digest()
    )

    return secret


# ============================================================
# 3. ENCRYPT MESSAGE
# ============================================================
#
# The ECC shared secret is now used as the AES key.
#
# AES-EAX gives us:
#
#       ciphertext
#       authentication tag
#
# The nonce is automatically generated by AES.
#
# We must keep the nonce because the receiver needs it
# for decryption.
#
# ============================================================

def encrypt_message(message, aes_key):

    cipher = AES.new(aes_key, AES.MODE_EAX)

    ciphertext, tag = cipher.encrypt_and_digest(message)

    nonce = cipher.nonce

    return ciphertext, nonce, tag


# ============================================================
# 4. DECRYPT MESSAGE
# ============================================================
#
# Receiver needs:
#
#       AES key
#       ciphertext
#       nonce
#       tag
#
# decrypt_and_verify():
#
#       1. decrypts ciphertext
#       2. verifies authentication tag
#
# If the ciphertext was modified, verification fails.
#
# ============================================================

def decrypt_message(ciphertext, nonce, tag, aes_key):

    cipher = AES.new(
        aes_key,
        AES.MODE_EAX,
        nonce=nonce
    )

    plaintext = cipher.decrypt_and_verify(
        ciphertext,
        tag
    )

    return plaintext


# ============================================================
# 5. COMPLETE HYBRID ENCRYPTION FUNCTION
# ============================================================
#
# This function represents the SENDER's side.
#
# Steps:
#
#       Generate sender keys
#       Generate receiver keys
#       Generate shared secret
#       Encrypt using AES
#
# ============================================================

def secure_encrypt(message, sender_private, receiver_public):

    # ECC key agreement
    shared_secret = generate_shared_secret(
        sender_private,
        receiver_public
    )

    # AES encryption
    ciphertext, nonce, tag = encrypt_message(
        message,
        shared_secret
    )

    return ciphertext, nonce, tag


# ============================================================
# 6. COMPLETE HYBRID DECRYPTION FUNCTION
# ============================================================
#
# This represents the RECEIVER's side.
#
# Receiver uses:
#
#       receiver private key
#              +
#       sender public key
#
# to generate the SAME shared secret.
#
# Then AES decrypts the message.
#
# ============================================================

def secure_decrypt(
    ciphertext,
    nonce,
    tag,
    receiver_private,
    sender_public
):

    # Generate SAME shared secret
    shared_secret = generate_shared_secret(
        receiver_private,
        sender_public
    )

    # AES decryption + authentication
    plaintext = decrypt_message(
        ciphertext,
        nonce,
        tag,
        shared_secret
    )

    return plaintext


# ============================================================
# MAIN PROGRAM
# ============================================================

print("========== ECC + AES ==========")


# ------------------------------------------------------------
# STEP 1: GENERATE RECEIVER ECC KEYS
# ------------------------------------------------------------

receiver_private, receiver_public = generate_ecc_keys()


# ------------------------------------------------------------
# STEP 2: GENERATE SENDER ECC KEYS
# ------------------------------------------------------------

sender_private, sender_public = generate_ecc_keys()


# ------------------------------------------------------------
# STEP 3: MESSAGE
#
# This is the part that changes according to the question.
#
# Lab example:
#       "Secure Transactions"
#
# Other possible scenarios:
#
#       "Patient Records"
#       "Bank Transaction"
#       "Confidential File"
#       "Secure Data"
#
# ------------------------------------------------------------

message = b"Secure Transactions"


# ------------------------------------------------------------
# STEP 4: SENDER ENCRYPTS
#
# Sender uses:
#
#       sender private
#              +
#       receiver public
#
# ------------------------------------------------------------

ciphertext, nonce, tag = secure_encrypt(
    message,
    sender_private,
    receiver_public
)


# ------------------------------------------------------------
# STEP 5: RECEIVER DECRYPTS
#
# Receiver uses:
#
#       receiver private
#              +
#       sender public
#
# This produces the SAME shared secret.
#
# ------------------------------------------------------------

plaintext = secure_decrypt(
    ciphertext,
    nonce,
    tag,
    receiver_private,
    sender_public
)


# ------------------------------------------------------------
# OUTPUT
# ------------------------------------------------------------

print("Original message :", message.decode())
print("Ciphertext       :", ciphertext.hex())
print("Decrypted message:", plaintext.decode())


# ------------------------------------------------------------
# VERIFICATION
#
# If the question says:
# "Verify that the original message is recovered."
# ------------------------------------------------------------

if message == plaintext:
    print("Verification     : SUCCESS")
else:
    print("Verification     : FAILED")
